---
- name: Grade for logins
  hosts: utilities
  gather_facts: false
  become: true    
  tasks:   
    - name: Setup strong passwords
      set_fact:
        gitlab_server_user_token: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"
           
    - name: Generate gitlab token
      command: >-
        gitlab-rails runner "
        token = User.find_by_username('root').personal_access_tokens.create(scopes: [:api], 
        name: 'Grade Token'); 
        token.set_token('{{ gitlab_server_user_token }}'); 
        token.save!
        "

- name: Grade playbook
  hosts: bastions
  gather_facts: false
  become: false
  tasks:

### Gitlab test
    - set_fact:
        gitlab_server_user_token: "{{ hostvars['utility.example.com']['gitlab_server_user_token'] }}"

    - name: Create Test webhook in gitlab
      uri: 
        url: http://utility.example.com//api/v4/projects/1/hooks/
        method: GET
        headers:
          PRIVATE-TOKEN: "{{ gitlab_server_user_token }}"
      register: gitlab_webhook_list
           
    - set_fact:
        gitlab_webhook_urls: "{{ gitlab_webhook_urls | d([]) + [ item.url ] }}"
      loop: "{{ gitlab_webhook_list.json }}"
           
    - debug: var=gitlab_webhook_urls

### Credentials test  
    - name: Credential's List
      uri: 
        url: https://{{ tower_hostname }}/api/v2/credentials/
        user: devops
        password: "{{ tower_admin_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: credential_list

    - set_fact:
        credential_names : "{{ credential_names |d([]) + [ item.id  | string + ':' + item.name ] }}"
      loop: "{{ credential_list.json.results }}"

    - name: find id of gitlab_token credentials
      set_fact: 
        gitlab_token_id: "{{ item.split(':')[0] }}"
      loop: "{{ credential_names }}"
      when: '"gitlab_token" in item'

#### Tower webhooks
          
    - name: Jobtemplate list
      uri: 
        url: https://{{ tower_hostname }}/api/v2/job_templates/
        user: devops
        password: "{{ tower_admin_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: jobtemplate_list

    - name: find id for Prod job template
      set_fact: 
        test_job_template_id: "{{ item.id }}"
      loop: "{{ jobtemplate_list.json.results }}"
      when: '"Test" in item.name' 

    - name: find id for Prod job template
      set_fact: 
        prod_job_template_id: "{{ item.id }}"
      loop: "{{ jobtemplate_list.json.results }}"
      when: '"Prod" in item.name'    
         
    - name: Jobtemplate webhook key
      loop: "{{ jobtemplate_list.json.results }}"
      uri: 
        url: https://{{ tower_hostname }}/api/v2/job_templates/{{ item.id }}/webhook_key/
        user: devops
        password: "{{ tower_admin_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: jt_webhook
           
    - set_fact:
        jobtemplate_webhooks : "{{ jobtemplate_webhooks |d([]) + [ item.json.webhook_key | string + '--' + item.url | replace('webhook_key','gitlab')  ] }}"
      loop: "{{ jt_webhook.results }}"
           
    - debug: 
        msg: "{{ item.id }}:{{ item.name}}"
        verbosity: 2
      loop: "{{ jobtemplate_list.json.results }}"

    - debug: var=jobtemplate_webhooks

## smoke test
    - name: Smoke test for Test Env
      uri:
        url: http://testserver.example.com/?name=root
        return_content: yes
      register: test_result

    - debug:
        msg: "Test Env Success"
      when: '"root redhat /bin/bash /root" in test_result.content'

    - name: Smoke Test for Prod Env
      uri:
        url: http://frontend.example.com/?name=root
        return_content: yes
      register: prod_result

    - debug:
        msg: "Prod Env Success"
      when: '"root redhat /bin/bash /root" in prod_result.content'
...