---        
- name: Grade for logins
  hosts: utilities
  gather_facts: false
  become: true    
  tasks:   
    - name: Setup strong passwords
      set_fact:
        gitlab_server_user_token: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits') }}"
           
    - command: >-
        gitlab-rails runner "
        token = User.find_by_username('devops').personal_access_tokens.create(scopes: [:read_api, :read_repository], 
        name: 'Automation token'); 
        token.set_token('{{ gitlab_server_user_token }}'); 
        token.save!
        "  
       
- name: Grade for logins
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars.yml
  tasks:   
    - set_fact:
        gitlab_server_user_token: "{{ hostvars['utility.example.com']['gitlab_server_user_token'] }}"
    - name: cred
      uri: 
        url: https://{{ tower_hostname }}/api/v2/credentials/
        user: devops
        password: "{{ tower_admin_password }}"
        method: POST
        body_format: json
        force_basic_auth: yes
        validate_certs: false
        status_code: 201
        body: >-
          {
              "name": "gitlab_token",
              "description": "Gitlab Personal Access Token",
              "organization": 1,
              "credential_type": 13,
              "inputs": {
                  "token": "{{ gitlab_server_user_token }}"
              },
              "user": null,
              "team": null
          }

    - shell: tower-cli job_template list | egrep "^[[:digit:]]" |cut -f1 -d " "
      register: jt_list
           
    # - debug: var=jt_list
           
    - command: tower-cli job_template delete {{ item }}
      loop: "{{ jt_list.stdout_lines }}"
           
    - name: Create Jobtemplate
      loop: "{{ tower_job_templates }}"
      register: jt_output
      uri: 
        url: https://{{ tower_hostname }}/api/v2/job_templates/
        user: devops
        password: "{{ tower_admin_password }}"
        method: POST
        body_format: json
        force_basic_auth: yes
        validate_certs: false
        status_code: 201
        body: >-
          {
            "name": "{{ item.name }}",
            "description": "{{ item.description }}",
            "job_type": "run",
            "inventory": 3,
            "project": 11,
            "playbook": "playbook.yml",
            "become_enabled": true,
            "allow_simultaneous": true,
            "webhook_service": "gitlab",
            "webhook_credential": 10
           
          }
           
    #- debug: var=jt_output
    - name: Associate host credential to Jobtemplate
      loop: "{{ jt_output.results }}"
      uri: 
        url: https://{{ tower_hostname }}/api/v2/job_templates/{{ item.json.id }}/credentials/
        user: devops
        password: "{{ tower_admin_password }}"
        method: POST
        body_format: json
        force_basic_auth: yes
        validate_certs: false
        status_code: 204
        body: '{ "id": 3 }'

    - name: Jobtemplate
      loop: "{{ jt_output.results }}"
      uri: 
        url: https://{{ tower_hostname }}/api/v2/job_templates/{{ item.json.id }}/webhook_key/
        user: devops
        password: "{{ tower_admin_password }}"
        method: GET
        force_basic_auth: yes
        validate_certs: false
        body_format: json
        status_code: 200
      register: jt_webhook
           
    - debug:
        msg: "{{ item.json.webhook_key }}"
      loop: "{{ jt_webhook.results }}"