---
- name: Using roles for test conditions
  hosts: all
  gather_facts: false
  become: false
  vars:
    error_message: []

  tasks:

    - name: log to file
      lineinfile:
        create: yes
        path: /tmp/opentlc_log
        insertafter: EOF
        line: "{{ inventory_hostname }}, User didnt exist"
      delegate_to: localhost  


    - set_fact:
        log: "{{ lookup('file', '/tmp/opentlc_log') }}"      
      delegate_to: localhost  
      run_once: true

    - name: get the file contents
      command: cat /tmp/opentlc_log
      register: my_items
      delegate_to: localhost  

    - name: print items
      debug:
        msg: "item is {{ item }}"
      with_items: "{{ my_items.stdout_lines }}"
      delegate_to: localhost  
      run_once: true

    - name: Set fact with log
      set_fact:
        opentlc_log: "{{ ( opentlc_log | default([])) +  [( item )] }}"
      with_items: "{{ my_items.stdout_lines | sort }}"
      delegate_to: localhost  
      run_once: true

    - name: output logfile   
      debug:
        var: opentlc_log
      delegate_to: localhost  
      run_once: true

#    V- name: loop throug log  
#      debug:
#        var: "{{ item }}"
#      with_lines: cat /tmp/opentlc_log
#      delegate_to: localhost  
#      run_once: true
