---
- name: Appends lab message to grader log
  lineinfile:
    create: yes
    insertafter: EOF
    path: "{{ opentlc_student_grader_log }}"
    line: "{{ grader_output_message }}"
  delegate_to: localhost

  #- when: grader_step == "PASS"
- when: grader_step is match("PASS.*)
  name: Appends lab message to success log
  lineinfile:
    create: yes
    insertafter: EOF
    path: "{{ opentlc_student_success_file }}"
    line: "{{ grader_output_message }}"
  delegate_to: localhost

  #- when: grader_step == "FAIL"
- when: grader_step is match("FAIL.*)
  name: Appends lab failure message to error log
  lineinfile:
    create: yes
    insertafter: EOF
    path: "{{ opentlc_student_error_file }}"
    line: "{{ grader_output_message }}"
  delegate_to: localhost
...
