---

- name: Gather local facts for simple access to opentlc metadata
  setup:
    gather_subset: local
    
- name: Set facts for simple access to opentlc metadata
  set_fact:
    opentlc_student: "{{ hostvars['localhost']['ansible_local']['opentlc']['ftl']['opentlc_student'] }}"

- name: Logging and debug course name and lab number
  debug:
    msg:
      - "Course name: {{ course_name }}"
      - "Lab Number: {{ lab_number }}"
    verbosity: 2

- name: "Remove existing {{ opentlc_log_file }}"
  file:
    path: "{{ opentlc_log_file }}"
    state: absent

#- name: "Create {{ opentlc_log_file }}"
#  file:
#    path: "{{ opentlc_log_file }}"
#    state: touch

- name: "Does {{ opentlc_error_log_file }} exist"
  stat:
    path: "{{ opentlc_error_log_file }}"
  register: r_error_file

- name: Clean up error log files
  block:

    - name: "Copy existing {{ opentlc_error_log_file }} to previous"
      copy:
        remote_src: yes
        force: yes
        src: "{{ opentlc_error_log_file }}"
        dest: "{{ opentlc_error_log_file_previous }}"

    - name: "Move existing {{ opentlc_error_log_file }}"
      file: 
        path: "{{ opentlc_error_log_file }}"
        state: absent

  when: r_error_file.stat.exists
...    
