---

- name: Gather local facts for simple access to opentlc metadata
  setup:
    gather_subset: local
    
- name: Set facts for simple access to opentlc metadata
  set_facts:
    opentlc_student: "{{ hostvars['localhost']['ansible_local']['opentlc']['ftl']['opentlc_student'] }}"

- name: Logging and debug course name and lab number
  debug:
    msg:
      - "Course name: {{ course_name }}"
      - "Lab Number: {{ lab_number }}"
    verbosity: 2

- name: "Remove existing {{ opentlc_log_file }}"
  file:
    path: "{{ opentlc_log_file }}"
    state: absent

- name: "Create {{ opentlc_log_file }}"
  file:
    path: "{{ opentlc_log_file }}"
    state: touch
...    
