---
- name: Logging and debug course name and lab number
  debug:
    msg:
      - "Course name: {{ course_name }}"
      - "Lab Number: {{ lab_number }}"
    verbosity: 2

- name: "Remove existing {{ opentlc_log_file }}"
  file:
    path: "{{ opentlc_log_file }}"
    state: absent

- name: "Create {{ opentlc_log_file }}"
  file:
    path: "{{ opentlc_log_file }}"
    state: touch
...    
