- hosts:
    - localhost
  connection: local
  gather_facts: no
  tasks:
    - name: running section1
      debug:
        msg: "Running Section1"
    - set_fact:
        grade_temp_section2_1: "PASS"
        grade_reason_section2_1: ""


- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

- import_playbook: ./solve_section2.yml
  when: solve == "true"

- name: Verify Section2
  hosts: apps
  gather_facts: no
  tasks:
  - name: Run a Curl Test against Frontend
    uri:
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: webpage
    ignore_errors: yes
  - debug: var=webpage
  
  - name: set grade to fail
    set_fact:
        grade_temp_section2_1: FAIL
        grade_reason_section2_1: "{{hostvars['localhost']['grade_reason_section2_1']}},{{inventory_hostname}} Webpage is not having correct content"     
    when:  ( webpage.status == -1 )  or ("'has been customized using Ansible' not in webpage.content")
    delegate_to: localhost
    delegate_facts: True
    ignore_errors: yes

  - name: Success if 'has been customized using Ansible' is in the page content
    debug: 
      msg: "Success: has been customized using Ansible' is in the page content"
    when: "'has been customized using Ansible' in webpage.content"
    ignore_errors: yes