  
- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

- import_playbook: ./solve_section1.yml
  when: solve == "true"

- name: Verify Section1
  hosts: apps
  gather_facts: no
  tasks:
  # - name: Initialize variables
  #   set_fact:
  #       result:
  #         -
  #       reason:
  #         -
    # delegate_to: localhost
    # delegate_facts: True
 
  - name: Run a Curl Test against Frontend
    uri:
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: webpage
    ignore_errors: yes
  - debug: var=webpage.content
  # - debug: var=hostvars['localhost']['array']['section1']['result']
  - name: set grade to fail
    set_fact:
      result:  
        - 'Fail' 
      reason: 
        - "{{inventory_hostname}} Webpage is not having correct content"
    when:  ( webpage.status == -1 )  or ("'Example' not in webpage.content")
    # delegate_to: localhost
    # delegate_facts: True    

  - name: set grade to pass
    set_fact:
      result:  
        - "PASS" 
      reason: 
        - "{{inventory_hostname}} {{ webpage.content }}"
    when:  ("Example" in webpage.content)
    
  - debug: var=reason
  - debug: var=result


- name: append grade list from section1
  hosts: localhost
  set_fact:
    array:
      section1:
         result: 
            - "{{ hostvars['app1'][result] }}"
            - "{{ hostvars['app2'][result] }}"
          reason:
            - "{{ hostvars['app1'][reason] }}"
            - "{{ hostvars['app2'][reason] }}"

      grade_status: "{{grade_status | combine( array )}}"
    
 