  
- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

- import_playbook: ./solve_section1.yml
  when: solve == "true"

- name: Verify Section1
  hosts: apps
  gather_facts: no
  tasks:
  
 
  - name: Run a Curl Test against Frontend
    uri:
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: webpage
    ignore_errors: yes
  # - debug: var=webpage.content
 
  - name: set grade to fail
    set_fact:
      result: 'Fail' 
      reason: "{{inventory_hostname}} Webpage is not having correct content"
    when:  ( webpage.status == -1 )  or ("'Example' not in webpage.content") or
           ( webpage.status == -1 )  or ("'has been customized using Ansible' not in webpage.content")
       

  - name: set grade to pass
    set_fact:
      result: "PASS" 
      reason: "{{inventory_hostname}} {{ webpage.content }}"
    when:  ("Example" in webpage.content) or
           ("has been customized using Ansible" in webpage.content)
    
  # - debug: var=reason
  # - debug: var=result


- name: append grade list from section1
  hosts: localhost
  tasks:
  - name: setting up section1 array
    set_fact:
      array:
        section1:
          result: 
              - "{{ hostvars['app1']['result'] }}"
              - "{{ hostvars['app2']['result'] }}"
          reason:
              - "{{ hostvars['app1']['reason'] }}"
              - "{{ hostvars['app2']['reason'] }}"

  -  set_fact:   
      grade_status: "{{ grade_status | combine(array) }}"


 