- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

###############     Play for solutions  ###############
- import_playbook: ./solve_section2.yml
  when: solve == "true"

###############  Play1 to reset arrays  ###############
- hosts: all
  tasks:
    - name: array
      set_fact:
        result: [] 
        reason: []
        assessment_result: []
###############     Play1 for grade     ###############
- name: Verify Section2
  hosts: apps
  gather_facts: True
  tasks:
  
#****************************#
########## Grade 1 ########### 
#****************************# 
  - name: Run a Curl Test against Frontend
    uri:
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: webpage
    ignore_errors: yes
  - debug: var=webpage.content
 
#### condiation1 Fail ####
  - name: set grade to fail
    set_fact:
      result: "{{ result + [ inventory_hostname + ' : FAIL' ] }}" 
      reason: "{{ reason + [ inventory_hostname + ' : Webpage does not have correct content.' ] }}"
    when:  ( webpage.status == -1 )  or ("'Example' not in webpage.content") or
           ( webpage.status == -1 )  or ("'has been customized using Ansible' not in webpage.content")
       
#### condiation1 Psss ####
  - name: set grade to pass
    set_fact:
      result: "{{ result + [ inventory_hostname + ' : PASS' ] }}" 
      reason: "{{ reason + [ inventory_hostname + ' : ' + webpage.content  ] }}"
    when:  ("Example" in webpage.content) or
           ("has been customized using Ansible" in webpage.content)
    
  # - debug: var=reason
  # - debug: var=result
#******************* Concatenate list, Must be included at the end of each play in playbook ***********************#
  - name: Include concatenate assessment_result role in play1
    include_role: 
      name: assessment_result
 # - debug: var=assessment_result
#************************        End of Concatenate list, Must be included         ********************************#

############## Play for Adding variable back to localhost ##############################
- name: append grade list from section2
  hosts: localhost
  tasks:
  - name: setting up section2 array
    set_fact:
      array:
        section2:
          result: 
              - "{{ hostvars['app1']['result'] }}"
              - "{{ hostvars['app2']['result'] }}"
          reason:
              - "{{ hostvars['app1']['reason'] }}"
              - "{{ hostvars['app2']['reason'] }}"
          assessment_result:
              - "{{ hostvars['app1']['assessment_result'] }}"
              - "{{ hostvars['app2']['assessment_result'] }}"

  -  set_fact:   
      grade_status: "{{ grade_status | combine(array) }}"



 