- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

- import_playbook: ./solve_section2.yml
  when: solve == "true"

- name: Verify Section2
  hosts: apps
  gather_facts: no
  tasks:
  
  - name: Run a Curl Test against Frontend
    uri:
      url: http://{{ inventory_hostname }}
      return_content: yes
    register: webpage
    ignore_errors: yes
 
  - debug: var=webpage
  
  - name: set grade to fail
    set_fact:
      result: FAIL 
      reason: "{{inventory_hostname}} Webpage is not having correct content}}"
    when:  ( webpage.status == -1 )  or ("'has been customized using Ansible' not in webpage.content")
    
  - name: set grade to pass
    set_fact:
      result: "PASS"
      reason: "{{ inventory_hostname }} {{ webpage.content }}"
    when: ("has been customized using Ansible" in webpage.content)

  - name: concatinate result and reason
    set_fact:
        array:
          section2:
            result: " {{ result }}"
            reason: " {{ hostvars[item]reason }} "
    loop: 
        - "{{ groups['apps'] }}"

  - debug: var=array

  - name: append grade list from section2
    set_fact:
        grade_status: "{{hostvars['localhost']['grade_status']|combine(array)}}"
    delegate_to: localhost
    delegate_facts: True
 
    