---
- name: "Checking {{ course_name }} lab {{ lab_num }}"
  hosts: bastion
  become: true
  gather_facts: false
  ignore_errors: yes
  vars:
    failed_test_reason: []
    failed_test_counter: 0
    test_counter: 0

  tasks:

    - name: Check mode block - don't fix student errors
      block:

        - name: Test Ansible is installed on bastion
          block:

            - name: Lab02 Section S2.1  Is ansible installed
              yum:
                name: ansible
                state: present
              register: last_task

            - name: Log failed test
              set_fact:
                failed_test_reason: "{{ failed_test_reason }} + ['Ansible package not present on bastion']"
                failed_test_counter: "{{ failed_test_counter | int + 1 }}"   
              when: last_task.rc != 0


        - name: Test user devops exists on bastion
          block:

            - name: Lab02 Section S2.2  Does user devops exist
              user:
                name: devops
                state: present

            - name: Log failed test
              set_fact:
                failed_test_reason: "{{ failed_test_reason }} + ['User devops not present on bastion']"
                failed_test_counter: "{{ failed_test_counter | int + 1 }}"   
              when: last_task.rc != 0


        - name: Debugging structure for outputting current status
          debug:
            msg: 
              - "Failed Task Reason: {{ failed_tests }}"
              - "Number of failed tests: {{ test_counter }}"  

        - name: Alternative construct to previous task - using block
          block:
            - name: Lab02 Section S2.2  Does user devops exist
              user:
                name: devooooops
                state: present
            - set_fact:
                current_task: passed
          rescue:     
            - debug:
                msg: "Woops"
            - set_fact:
                current_task: failed



        - name: Lab02 Section 2.2 Does ssh key exist for user devops
          stat:
            path: /home/devops/.ssh/id_rsa.pub
          register: key_stat  
          changed_when: key_stat.stat.exists == False

        - name: Lab02 Section 2.2 Should fail - FAKE Does ssh key exist for user devops
          stat:
            path: /home/devops/.ssh/iiiiiid_rsa.pub
          register: key_stat  
          changed_when: key_stat.stat.exists == False

      vars:    
        ansible_check_mode: True
...
