---
- name: setting up section2 array
  set_fact:
    array:
      section1:
        result: 
            - "{{ hostvars['app1']['result'] }}"
            - "{{ hostvars['app2']['result'] }}"
        reason:
            - "{{ hostvars['app1']['reason'] }}"
            - "{{ hostvars['app2']['reason'] }}"

-  set_fact:   
    grade_status: "{{ grade_status | combine(array) }}"