---
- name: Grade lab Homework of OpenShift Advanced Infrastructure Deployment
  hosts: localhost
  gather_facts: false
  become: false

  # All lab tests go here
  tasks:
  - name: Set GUID
    set_fact:
      guid: "{{ lookup('env','GUID') }}"

  - name: Check if there are 3 masters
    include_role:
      name: grader_check_ocp_node_label
    vars:
      node_label: "node-role.kubernetes.io/master="
      node_count: 3
      task_description_message: Check if the cluster has 3 masters
      student_error_message: "The cluster doesn't have 3 masters"

  - name: Check if there are 2 infra
    include_role:
      name: grader_check_ocp_node_label
    vars:
      node_label: "node-role.kubernetes.io/infra="
      node_count: 2
      task_description_message: Check if the cluster has 2 infra nodes
      student_error_message: "The cluster doesn't have 2 infra nodes"

  - name: Check if there are 2 workers
    include_role:
      name: grader_check_ocp_node_label
    vars:
      node_label: "node-role.kubernetes.io/worker="
      node_count: 4  # because infra are workers too
      task_description_message: Check if the cluster has 2 worker nodes
      student_error_message: "The cluster doesn't have 2 worker nodes"

      
  - name: Check if 5 user identities exist
    include_role:
      name: grader_check_ocp_identity
    vars:
      id_count: 5
      task_description_message: Check if 5 user identities exist
      student_error_message: "The cluster doesn't have 5 user identities"

  - name: Check if john is a cluster admin
    include_role:
      name: grader_check_oc_command
    vars:
      oc_command: "auth can-i list nodes --as john"
      task_description_message: Check if john is a cluster admin
      student_error_message: "User john is not a cluster admin"

#
#  - name: Create a project test-hw-project
#
  - name: Check LimitRange in project george-test
    include_role:
      name: grader_check_ocp_resource
    vars:
      resource_kind: LimitRange
      resource_namespace: george-test
      resource_name: project-limits
      task_description_message: Check LimitRange in project george-test
      student_error_message: "LimitRange project-limits doesn't exist in project george-test"

  - name: Check ResourceQuota in project george-test
    include_role:
      name: grader_check_ocp_resource
    vars:
      resource_kind: ResourceQuota
      resource_namespace: george-test
      resource_name: project-quota
      task_description_message: Check ResourceQuota in project george-test
      student_error_message: "ResourceQuota project-quota doesn't exist in project george-test"

  - name: Check NetworkPolicy allow-same-namespace in project george-test
    include_role:
      name: grader_check_ocp_resource
    vars:
      resource_kind: NetworkPolicy
      resource_namespace: george-test
      resource_name: allow-same-namespace
      task_description_message: Check NetworkPolicy allow-same-namespace in project george-test
      student_error_message: "NetworkPolicy allow-same-namespace doesn't exist in project george-test"

  - name: Check NetworkPolicy allow-from-openshift-ingress in project george-test
    include_role:
      name: grader_check_ocp_resource
    vars:
      resource_kind: NetworkPolicy
      resource_namespace: george-test
      resource_name: allow-from-openshift-ingress
      task_description_message: Check NetworkPolicy allow-from-openshift-ingress in project george-test
      student_error_message: "NetworkPolicy allow-from-openshift-ingress doesn't exist in project george-test"


