---
- name: Log grader task result
  include_role:
    name: ftl_TEST_log_grade_to_log
  vars:
    grader_output_message: "{{ grader_test_failed + ', ' + \
                            task_description_message +\
                            ', (' + inventory_hostname + ')'  }}"
...
