---
- name: Initialize grading report
  hosts: localhost
  gather_facts: false
  become: true

  tasks: 

    - name: Initilize logging
      import_role: 
        name: ftl_run_lab_logger
      vars:
        logger_init: true

    - name: Logging and debug course name and lab number    
      debug:
        msg:
          - "Course name: {{ course_name }}"
          - "Lab Number: {{ lab_number }}"  
        verbosity: 2    

- name: Import and run the grading playbook
  import_playbook: "./courses/{{ course_name }}/lab_{{ lab_number }}/grade_lab.yml"
  tags:
    - lab_grader

- name: Run grading report
  hosts: localhost
  gather_facts: false
  become: true

  tasks: 

    - name: Update LMS and Student
      import_role: 
        name: ftl_run_lab_logger
      vars:
        logger_finish: true
...
