---
- name: Run FTL Init role - initialize grading report data structures
  hosts: localhost
  gather_facts: false
  become: true

  roles:

    - when: purpose == "grade"
      name: ftl_run_init

- name: "Import and run the {{ purpose }} playbooks"
  import_playbook: "./courses/{{ course_name }}/lab_{{ lab_number }}/{{ purpose }}_lab.yml"

- name: Run FTL finish role - generate reports and updates
  hosts: localhost
  gather_facts: false
  become: true

  roles:
    - when: purpose == "grade"
      name: ftl_run_finish
...
