---
- name: Run FTL Init role - initialize grading report data structures
  hosts: localhost
  gather_facts: false
  become: false
  tags:
    - ftl-init

  roles:

    - when: purpose == "grade_lab"
      name: ftl_run_init
#      apply:
#        tags:
#          - ftl-init

- name: "Import and run the {{ purpose }} playbooks"
  import_playbook: "./courses/{{ course_name }}/lab_{{ lab_number }}/{{ purpose }}.yml"

- name: Run FTL finish role - generate reports and updates
  hosts: localhost
  gather_facts: false
  become: false

  roles:
    - when: purpose == "grade_lab"
      name: ftl_run_finish
...
