- name: just print the var from callling playbook
  debug:
    msg: "Calling var is {{ file_with_path }} on host {{ ansible_host }}"

- name: Create logging message fact
  set_fact:
    grader_output_message: "{{ inventory_hostname + ', '\
    + task_description_message }}"
  delegate_to: localhost
