---
# Stage 1: Run the grader test

- name: Run a command and collect response
  command: "{{ command }}"
  register: r_command

- name: Output command register
  debug:
    var: r_command
    verbosity: 2

# Stage 2: Set if error or not - often register.failed == true

- name: Set if last task indicated the student SUCCEEDED in that test
  set_fact: 
    last_test_failed: false
  when: command_response in r_command.stdout

- name: Set if last task indicated the student FAILED that test
  set_fact:
    last_test_failed: true
  when: command_response not in r_command.stdout

# Stage 3: Call the event logger

- name: Call the error event logging role
  import_role:
    name: ftl_run_log_grader_event
...
