---
- name: Grade lab 04_1 of OpenShift 4 Configuration
  hosts: localhost
  gather_facts: false
  become: false

  # All lab tests go here
  tasks:
    - name: Get deployments
      k8s_facts:
        api_version: apps/v1
        kind: Deployment
        name: example
        namespace: resourcemanagement
      register: r_deployment
    
    - name: Check for example deployment
      debug:
        msg: "Success"
      