---
- name: Grade lab 03 01 of Ansible Engine Foundations
  hosts: web
  gather_facts: false
  become: true
  vars:
    course_name: Ansible Engine Foundations

  pre_tasks: 

    - name: Update LMS and Student
      import_role: 
        name: ftl_run_start
      run_once: true
      delegate_to: localhost

  roles:      # All lab tests go here

    - name: Section 5.1, Check student has installed Apache
      role: ftl_check_package_installed
      vars:
        section_number: 5.1
        student_error_message: Package httpd not installed
        package: httpd

    - name: Section 5.2, Check student has enabled Apache
      role: ftl_check_service_enabled
      vars:
        section_number: 5.2
        student_error_message: Package httpd not installed
        service: httpd

    - name: Section 5.3, Check student has enabled Apache
      role: ftl_check_service_enabled
      vars:
        section_number: 5.3
        student_error_message: Package eieio not installed
        service: eieio

  post_tasks: 

    - name: Update LMS and Student
      import_role: 
        name: ftl_run_finish_grading
      run_once: true
      delegate_to: localhost
