  
- name: infra-ec2-wait_for_linux_hosts
  hosts:
    - all:!windows
  become: true
  gather_facts: no
  roles:
  - { role: "infra-ec2-wait_for_linux_hosts" }

- import_playbook: ./solve_section1.yml
  when: solve == "true"

- name: Verify Section1
  hosts: apps
  gather_facts: no
  tasks:
   
  - name: Run a Curl Test against Frontend
    uri:
      url: http://{{ ansible_host }}
      status_code: 403,200,-1
      return_content: yes
    register: webpage

  # - debug: var=webpage.content
 
  - name: set grade to fail
    set_fact:
      result: 
        - "{{ inventory_hostname }} : Fail"
      reason: 
        - "{{inventory_hostname}} :  Webpage is not having correct content" 
    when: ( webpage.status == -1 )  or 
          ("'Hoorraaayyy!!! My first playbook ran successfully' not in webpage.content")

  - name: set grade to pass
    set_fact:
      result: 
        - "{{ inventory_hostname }} : PASS" 
      reason: 
        - "{{inventory_hostname}} : Hoorraaayyy!!! My first playbook ran successfully' is in the page content"
    when:  "'Hoorraaayyy!!! My first playbook ran successfully' in webpage.content"
    
  # - debug: var=reason
  # - debug: var=result

############## Play for Adding variable back to localhost ##############################
- name: append grade list from section1
  hosts: localhost
  roles:
  - role: adding_variable_to_localhost
    module: Lab02
    section: 01
  