---

python_dependencies:
  - python-pip

pip_dependencies:
  - virtualenv

# Home for the virtualenv
# Name for the grading virtualenv

virtual_env_home: /tmp/virtualenvs
virtual_env_name: venv-grading
...
