- name: Test user exists
  user_exists:
    user: "{{ user }}"
  ignore_errors: true
  register: r_user

- name: debug task
  debug:
    msg: "User {{ user }} does not exists!"
  when: r_user.failed == true

- name: Logging block
  block:

    - name: Capture and log error
      set_fact:
        error_message: '{{ "Section: " + ( section_number | string)  + ", " + inventory_hostname + ", " + student_error_message }}'
      delegate_to: localhost

    - name: Log event to log file
      import_role:
        name: log_grade_to_log
      delegate_to: localhost

  when: r_user.failed == true
