---
- name: Example of a role based lab checker with silent grading
  hosts: all
  gather_facts: false
  become: false
  vars:
    course_name: Ansible Integrations
    #    error_message: [] # get rid of this ugly construct

  roles:

    - name: Initilize grading run
      role: grade-init

    - name: Section 1.3, Check student has created file 
      role: opentlc_file_exists
      vars:
        section_number: 1.3
        student_error_message: /etc/foo does not exist
        file_with_path: /etc/foo

    - name: Section 1.4, Check student has created file 
      role: opentlc_file_exists
      vars:
        section_number: 1.4
        student_error_message: /etc/foo does not exist
        file_with_path: /etc/foo

    - name: Finish, generate grade, update LMS, and student
      role: finish
      delegate_to: localhost
      run_once: true
#
# Implement below as import?
# Authors don't need to touch anything from here on
#
        
- name: Report grading
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  roles:

    - name: Generate student grade report
      role: grade-report-generation

    - name: Show student grade    
      role: grade-show-student

    - name: Update LMS
      role: grade-update-lms
