---
- name: test module returning facts
  hosts: all
  gather_facts: false 
  vars:
    course_name_long: Ansible Implementation 2
    lab_number: 2
    #course_name_long: Ansible Implementation 2
 
  tasks: 
  
    - name: Setup opentlc_lab_score module
      opentlc_lab_score:
          failure_messages: []
          reason: ""
          init: True
      register: r_return
    
    - name: Log first failure
      opentlc_lab_score:
          failure_messages: "{{ rc_failure_messages }}"
          reason: "User devops does not exist"
          hostname: "{{ inventory_hostname }}"
      register: r_return
      delegate_to: localhost

    - name: Call return_facts module second time
      opentlc_lab_score:
          failure_messages: "{{ rc_failure_messages }}"
          reason: "2nd failure: ansible not installed }}"
          hostname: "{{ inventory_hostname }}"
      register: r_return

    - name: Call return_facts module second time
      opentlc_lab_score:
          failure_messages: "{{ rc_failure_messages }}"
          reason: "ssh keys missing for devops user"
          hostname: "{{ inventory_hostname }}"
      register: r_return

    - name: Output register variable from opentlc_lab_score
      debug:
        var: r_return

    - name: Loop over failures
      debug:
        msg: "Failed because: {{ item }}"
      loop: "{{ rc_failure_messages }}"  

    - name: Generate a report
      template:
        src: templates/lab_error_report.j2
        dest: "output/{{ inventory_hostname }}_lab_error_report.txt"
        #      delegate_to: localhost  
      vars:
        error_message: "{{ rc_failure_messages }}"

    - name: reference local fact
      debug:
        msg: "{{ ansible_facts['rc_failure_messages'] }}"

#    - name: Output register variable from opentlc_lab_score
#      debug:
#        var: r_return
...
