---
- name: Grade lab 03_1 of OpenShift 4 Application Deployment
  hosts: localhost
  gather_facts: false
  become: false

 # All lab tests go here
  tasks:
  - name: Determine current project
    shell: "oc project|awk '{print $3}'|tr -d '\"'"
    register: r_project
  - name: Check that the Gogs Config Map exists
    include_role:
      name: grader_check_ocp_configmap_exists
    vars:
      task_description_message: Check that the Gogs ConfigMap exists
      configmap_name: gogs
      project_name: "{{ r_project.stdout }}"
  - name: Check the Gogs Route exists
    include_role:
      name: grader_check_ocp_route_exists
    vars:
      task_description_message: Check that the Gogs route exists
      route_name: "gogs"
      project_name: "{{ r_project.stdout }}"