---
- name: Clone FTL git repo to grading host(s)
  git:
    repo: "{{ ftl_git_repo }}"
    dest: "{{ ftl_grading_host_home }}"
    force: yes
  no_log: true
  tags:
    - clone-ftl-repo

- name: "Create custom fact directory for student metadata"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Insert custom fact file"
  copy:
     src: opentlc.fact
     dest: /etc/ansible/facts.d/opentlc.fact
     mode: 0755
...
