---
- name: Clone FTL git repo to grading host(s)
  git:
    repo: "{{ ftl_git_repo }}"
    dest: "{{ ftl_grading_host_home }}"
    force: yes
  no_log: true
  tags:
    - clone-ftl-repo

- name: "Create custom fact directory for student metadata"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Insert opentlc custom facts e.g. student opentlc name"
  template:
     src: opentlc.fact.j2
     dest: /etc/ansible/facts.d/opentlc.fact
     mode: 0644

- name: Install grade scrip
  copy:
    file: grade_lab
    path: /usr/local/bin/grade_lab
    mode: 0555
...
