---
- name: Using roles for test conditions
  hosts: all
  gather_facts: false
  become: false
  vars:
    error_message: []

  roles:

    - name: Initilize Lab scoring
      role:     
    - name: Section 1.3, Check student has created file 
      role: opentlc_file_exists
      vars:
        path: /etc/foo
        error_reason: /etc/foo does not exist
        section_number: 1.3

    - name: Section 1.4, Check student has created file 
      role: opentlc_file_exists
      vars:
        path: /etc/foo
        error_reason: "Section 1.4, /etc/foo does not exist"


  post_tasks:

    - name: Output state of error_message
      debug:
        var: error_message
      delegate_to: localhost  
      run_once: true

    - name: Output state of error_message
      debug:
        var: error_message[0]
      delegate_to: localhost  
      run_once: true
