---
- name: Searching file for FAIL
  lineinfile:
    path: "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    regex: "^FAIL.*"
    state: absent
  check_mode: true
  register: r_lab_pass

- when: "{{ r_lab_pass.changed | bool }}"
  name: Report contains a fail
  set_fact:
    lab_passed: true
    student_errors: "{{ r_lab_pass.found }}"

- name: Output lab status and error count
  debug:
    msg: 
      - "student_failed = {{ student_failed }}"
      - "Error count = {{ student_errors }}"  
  verbosity: 2

- when: "{{ lab_passed | bool }}"
  name: Lab passed, update report 
  blockinfile:
    block: |
      SUCCESS
    dest:   "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    insertafter: EOF

- when: "{{ not lab_passed | bool }}"
  name: Lab failed, update report 
  blockinfile:
    block: |
      FAILURE
    dest:   "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    insertafter: EOF
...
