---
- name: get the file contents
  command: "cat {{ opentlc_log_file }}"
  register: r_opentlc_log

- name: Iterate through log file appending to fact
  set_fact:
    opentlc_log_content: "{{ ( opentlc_log_content | default([])) +  [( item )] }}"
  with_items: "{{ r_opentlc_log.stdout_lines | sort }}"

- name:  Generate student error report
  template:
    src: lab_error_report.j2
    dest: /tmp/error_report.txt

- name: output logfile   
  debug:
    var: opentlc_log_content
    
