---
- name: get the file contents
  command: "cat {{ opentlc_log_file }}"
  register: r_opentlc_log
  delegate_to: localhost  

- name: Set fact with log
  set_fact:
    opentlc_log: "{{ ( opentlc_log_file | default([])) +  [( item )] }}"
  with_items: "{{ r_opentlc_log.stdout_lines | sort }}"
  delegate_to: localhost  
  run_once: true

- name:  
  template:
    src: lab_error_report.j2
    dest: /tmp/error_report.txt

- name: output logfile   
  debug:
    var: opentlc_log
  delegate_to: localhost  
  run_once: true
