---
- name: Debug grader should always fail
  hosts: localhost
  connection: local
  gather_facts: false

  roles:      # All lab tests go here

    - name: Section 2
      role: grader_check_always_fail
      vars:
        student_error_message: Grader failed
        task_description_message: Run lab grader on grader host
...
