- hosts: bastions
  become: yes
  vars:
    file_and_password:
      vault-pass: redhat, 
      vault-pass-change: ansible 

    vault_file:
      super-secret.yml: vault-pass-change 
      super-secret-encrypted.yml: vault-pass  

  tasks:

  ####### Condition 1 ###################
    - name: Create User devops
      user: 
        name: devops
        state: present

    - name: Create Directory
      file: 
        path: ~devops/ansible_implementation
        state: directory
        mode: 0755  
        owner: devops
        group: devops

    - name: Create file
      copy:
        content: >
          This is encrypted.
          This is also encrypted.
        dest: ~devops/ansible_implementation/{{ item }}
        mode: 0644  
        owner: devops
        group: devops 
      loop: 
        - super-secret.yml
        - super-secret-decrypted.yml

    - name: Create Password file1
      copy:
        content: "{{ item.value }}"
        dest: ~devops/ansible_implementation/{{ item.key }}
        mode: 0644  
        owner: devops
        group: devops 
      loop: "{{ file_and_password |dict2items }}"

    - name: Encrypt file by ansible-vault
      shell: ansible-vault encrypt ~devops/ansible_implementation/{{item.0}} --vault-password-file=/home/devops/ansible_implementation/{{item.1}}
    
      loop: "{{ vault_file |dict2items }}"
    



    
