---
- name: Grade lab 01 01 of Ansible Implementation
  hosts: localhost
  connection: local
  gather_facts: false

  roles:      # All lab tests go here

    - name: Section 2
      role: grader_check_always_succeed
      vars:
        section_number: 6.4.1
        student_error_message: Package httpd not installed
        package: httpd

    - name: Section 6.4.2, Check student has enabled Apache
      role: ftl_check_service_started
      vars:
        section_number: 6.4.2
        student_error_message: Package httpd not started
        service: httpd
...
---
#- hosts: all
#  gather_facts: false
#
#  tasks:
#
#    - name: check for motd line
#      lineinfile:
#        path: /etc/motd
#        state: present
#        line: "Managed by Ansible"
#      check_mode: true
#      register: r_motd
#
#    - name: check for motd line
#      debug:
#        var: r_motd

