---
- name: Logging lab section PASS or FAIL to student grader report
  block:
    - when: success | bool
      name: Create Pass logging message
      set_fact:
        output_message: "PASS: {{ task_description_message }}"

    - when: not success | bool
      name: Create Fail logging message
      set_fact:
        output_message: "FAIL: {{ task_description_message }}: {{ student_error_message | d('') }}"

    - name: Appends lab check result message to grader log
      lineinfile:
        create: yes
        insertafter: EOF
        path: "{{ grader_working_dir }}/{{ grader_student_report_file }}"
        line: "{{ grader_output_message }}"
  delegate_to: localhost
...
