---
- name: "Check package {{ package }} installed"
  package:
    name: "{{ package }}"
    state: present
  check_mode: True
  register: r_state

#  
# Common logging logic - leave


- name: Capture and log error
  set_fact:
    error_message: "{{ 'Section: ' + ( section_number | string)  + ', '\
    + inventory_hostname + ', ' + student_error_message }}"
  delegate_to: localhost

- when: r_state.changed
  name: Import logging tasks
  import_role:
    name: ftl_run_log_grade_to_log
...
