---
- name: Show the namespace and deployment being evaluated
  debug:
    msg: "Checking if deployment '{{ deployment_name }}' exists in project '{{ project_name }}'"

- name: Get facts on deployment
  k8s_facts:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ project_name }}"
    name: "{{ deployment_name }}"
  register: r_deployment

- name: Check that the deployment exists
  set_fact:
    deployment_exists: false

- name: Check that the deployment exists
  set_fact:
    deployment_exists: true
  when:
    - item.metadata.name is match( deployment_name )
  loop: "{{ r_deployment.resources }}"

- name: Print success if deployment deployment exists
  debug:
    msg: "Success: Deployment '{{ deployment_name }}' found in project '{{ project_name }}'"
  when: deployment_exists|bool

- name: Fail if the deployment does not exist
  debug:
    msg: "Fail: Deployment '{{ deployment_name }}' not found in project '{{ project_name }}'"
  when: not deployment_exists|bool

######################################################
#                                                    #
# Common boiler plate logging logic - Do not modify  #
#                                                    #
######################################################

- name: Default to PASSED
  set_fact:
    f_grader_test_result: PASSED

- when: not deployment_exists|bool
  name: Test Failed
  set_fact:
    f_grader_test_result: FAILED
