---
- name: print out the route and namespace we are checking
  debug:
    msg: "Checking if route {{ route_name }} for application {{ app_name }} exists in project {{ project_name }}"

- name: check if the route exists
  k8s_facts:
    kind: Route
    namespace: "{{ project_name }}"
    label_selectors:
      - app = {{ app_name }}
  register: route_namespace

- name: logging block
  block:
    - debug:
        msg: "The route {{ route_name }} doesn't exist in project {{ project_name }}"
  when: route_namespace.resources[0].spec.host != route_name
