---
- name: Example of a role based lab checker with silent grading
  hosts: localhost
  gather_facts: false
  become: false

  tasks:

    - name: does file exist
      stat:
        path: /etc/hosts
      register: r_file_stat  

    - name: does file exist
      debug:
        var: r_file_stat.stat

    - name: file exists
      debug:
        msg: file exists
      when: r_file_stat.stat.exists == true

    - name: does file exist
      stat:
        path: /etc/hostsyhosty
      register: r_file_stat  


    - name: does not file exist
      debug:
        msg: file does not exist
      when: r_file_stat.stat.exists == false
