
- name: Step 001.1 Deploy Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step001
    - step001.1
  tasks:
    - name: debug instancesAAAA
      debug:
        var: item
      loop: "{{instances}}"


    - add_host:
        name: "{{item.name}}"
        ansible_host: "{{item.ansible_hostname}}"
        internal_hostname: "{{ item.ansible_internal }}"
        ansible_ssh_user: "{{item.ansible_ssh_user}}"
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: "{{ansible_ssh_private_key_file}}"
        group: "{{ item.groups }}"

      loop: "{{instances}}"
      tags:
        - create_inventory
        - must

    - name: debug groups
      debug:
        var: groups
        verbosity: 2
