---
- name: Step 0000 - Install Galaxy roles
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    # User can override this variable to specify a different requirements.yml, like:
    # -e requirements_path=.../requirements_prod.yml

## PS: ROLE_IMPROVE_TASK
## Needs to be validated
## var is called from main.yml
    requirements_path: "../courses/{{ course_name }}/requirements.yml"



  tasks:
    - name: Check if requirements.yml exists
      stat:
        path: "{{ requirements_path }}"
      register: r_requirements_stat

    - name: Import roles from requirements.yml
      command: >-
        ansible-galaxy install
        -r "{{ requirements_path }}"
        -p "../courses/{{ course_name }}/roles"
      when: r_requirements_stat.stat.exists
