---
- name: Grade lab 03_2 of OpenShift 4 Application Deployment
  hosts: localhost
  gather_facts: false
  become: false

 # All lab tests go here
  tasks:
  - name: Check the OpenShift Web Console Route exists
    include_role:
      name: grader_check_ocp_route_exists
    vars:
      task_description_message: Check that the Web Console route exists
      route_name: "console"
      project_name: "openshift-console"