---
- name: Grade lab 03_2 of OpenShift 4 Application Deployment
  hosts: localhost
  gather_facts: false
  become: false

 # All lab tests go here
  tasks:
  - name: Determine current project
    shell: "oc project|awk '{print $3}'|tr -d '\"'"
    register: r_project
  - name: Check the PrintEnv Route exists
    include_role:
      name: grader_check_ocp_route_exists
    vars:
      task_description_message: Check that the PrintEnv route exists
      route_name: "printenv"
      project_name: "{{ r_project.stdout }}"

# Maybe check that deployment config printenv.status.latestVersion >= 4